# Generated by Django 4.0 on 2022-01-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('Voltage', models.IntegerField()),
                ('Current', models.IntegerField()),
                ('Power', models.IntegerField()),
            ],
        ),
    ]
