# Generated by Django 4.0 on 2022-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcp',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
