# Generated by Django 4.0 on 2022-03-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_plcp_pf'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcp',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
