# Generated by Django 4.0 on 2022-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_plcp_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='plcp_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plcp',
            name='state',
        ),
    ]
